a

diff --git a/.github/workflows/selenium-java.yml b/.github/workflows/selenium-java.yml
--- a/.github/workflows/selenium-java.yml
+++ b/.github/workflows/selenium-java.yml
@@ -40,3 +40,16 @@ jobs:
 
       - name: Run Selenium tests
         run: mvn test
+        continue-on-error: true
+
+      # Upload target folder as artifact
+      - name: Upload Test Reports
+        uses: actions/upload-artifact@v3
+        with:
+          name: Selenium-Test-Reports
+          path: SelePractice/target
+
+      # Fail the job if tests failed
+      - name: Check test result
+        if: steps.run-tests.outcome != 'success'
+        run: exit 1
